# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Upload Artifacts

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/python-app.yml

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
      - name: publish-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./executable/RSGrapher.exe
          asset_name: RSGrapher.exe
          asset_content_type: application/octet-stream

